variables:
    DOCKER_IMAGE: registry.gitlab.com/krakcen/hugoworld-me

stages:
    - build
    - tests
    - deploy

build:
    image: docker:git
    stage: build
    services:
        - docker:dind
    before_script:
        - './scripts/build/before-build.sh'
    script:
        - './scripts/build/build.sh'
    only:
        - master

lint_tests:
    stage: tests
    script:
        - './scripts/tests/lint_tests.sh'

unit_tests:
    image: docker:git
    stage: tests
    services:
        - docker:dind
    before_script:
        - docker info
    script:
        - './scripts/tests/unit_tests.sh'

deploy:
    image: alpine:latest
    stage: deploy
    variables:
        PROTO_VAR: 'PROTO_VAR'
    before_script:
        - ./scripts/deploy/before-deploy-production.sh
    script:
        - ./scripts/deploy/deploy-production.sh
    only:
        - master
