image: python:3.7.4

variables:
    DOCKER_IMAGE: registry.gitlab.com/krakcen/hugoworld-me

stages:
    - tests
    - build
    - deploy

before_script:
    - docker info

lint_tests:
    stage: tests
    script:
        - './scripts/tests/lint_tests.sh'

unit_tests:
    stage: tests
    script:
        - './scripts/tests/unit_tests.sh'

build:
    stage: build
    before_script:
        - './scripts/build/before-build.sh'
    script:
        - './scripts/build/build.sh'
    only:
        - master

deploy:
    image: alpine:latest
    stage: deploy
    variables:
        PROTO_VAR: 'PROTO_VAR'
    before_script:
        - ./scripts/deploy/before-deploy-production.sh
    script:
        - ./scripts/deploy/deploy-production.sh
    only:
        - master
