version: '3'
services:
    yarn:
        image: 'node:13.8.0'
        ports:
            - '3000:3000'
        volumes:
            - '.:/usr/src/app'
        working_dir: '/usr/src/app'
        command: 'yarn dev'

